// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The collision policy chosen in the UI for Folder-mode extraction.
 *
 * The serde wire values are camelCase (`autoRename` / `skip` / `overwrite`) and
 * are pinned by [`tests::conflict_policy_serializes_to_camel_case_variants`].
 */
export type ConflictPolicy = "autoRename" | "skip" | "overwrite";
