// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

/**
 * A single draft item: its path and what kind of source it is.
 */
export type DraftItemDto = {
  /**
   * The item's filesystem path (lossy UTF-8).
   */
  path: string;
  /**
   * Whether the item is a folder, a rar, or a zip.
   */
  kind: SourceKind;
  /**
   * The base name this item's output is derived from, as computed by the
   * domain (`SourceItem::output_stem`). Shipped from Rust so the frontend
   * never re-derives it.
   */
  outputStem: string;
};
