// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

/**
 * A single draft item: its path and what kind of source it is.
 */
export type DraftItemDto = {
  /**
   * The item's filesystem path (lossy UTF-8).
   */
  path: string;
  /**
   * Whether the item is a folder, a rar, or a zip.
   */
  kind: SourceKind;
};
