// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictPolicy } from "./ConflictPolicy";
import type { DraftItemDto } from "./DraftItemDto";
import type { OutputMode } from "./OutputMode";

/**
 * A snapshot of the current draft (pending plan) shown in the UI.
 */
export type DraftSnapshot = {
  /**
   * The source items queued in the draft, in order.
   */
  items: Array<DraftItemDto>;
  /**
   * The naming template, if one has been set.
   */
  namingTemplate: string | null;
  /**
   * The sequence start number used to render output filenames (default 1).
   */
  startNumber: number;
  /**
   * The output directory, if one has been chosen.
   */
  outputDir: string | null;
  /**
   * The chosen output mode (re-zip vs extract-to-folder).
   */
  outputMode: OutputMode;
  /**
   * The chosen collision policy for Folder-mode extraction.
   */
  conflictPolicy: ConflictPolicy;
};
