// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A failed task paired with its human-readable reason.
 */
export type FailedTaskDto = { 
/**
 * The raw task id.
 */
taskId: number, 
/**
 * Why the task failed.
 */
reason: string, };
