// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedTaskDto } from "./FailedTaskDto";
import type { TaskResultDto } from "./TaskResultDto";

/**
 * The outcome of a finished job, adapted from [`JobSummary`] for the wire.
 */
export type JobSummaryDto = {
  /**
   * Raw ids of tasks that completed successfully, in job order.
   */
  succeeded: Array<number>;
  /**
   * Raw ids of tasks that were cancelled, in job order.
   */
  cancelled: Array<number>;
  /**
   * Tasks that failed, paired with their reason, in job order.
   */
  failed: Array<FailedTaskDto>;
  /**
   * Per-task results in job order, each carrying the task's absolute output
   * path and terminal status. Additive companion to the legacy
   * `succeeded`/`cancelled`/`failed` buckets: it is the single per-task
   * projection the completion UI uses to surface "where did my files go".
   */
  results: Array<TaskResultDto>;
};
