// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedTaskDto } from "./FailedTaskDto";

/**
 * The outcome of a finished job, adapted from [`JobSummary`] for the wire.
 */
export type JobSummaryDto = {
  /**
   * Raw ids of tasks that completed successfully, in job order.
   */
  succeeded: Array<number>;
  /**
   * Raw ids of tasks that were cancelled, in job order.
   */
  cancelled: Array<number>;
  /**
   * Tasks that failed, paired with their reason, in job order.
   */
  failed: Array<FailedTaskDto>;
};
