// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The batch output mode chosen in the UI.
 */
export type OutputMode = "zip" | "folder";
