// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressCounts } from "./ProgressCounts";
import type { TaskProgressDto } from "./TaskProgressDto";

/**
 * An aggregated progress snapshot, adapted from [`JobProgress`] for the wire.
 */
export type ProgressEvent = { 
/**
 * Summed byte counters across every task.
 */
overall: ProgressCounts, 
/**
 * Per-task progress in the job's task order.
 */
perTask: Array<TaskProgressDto>, 
/**
 * Time elapsed since the job started, in milliseconds.
 */
elapsedMs: number, };
