// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pair of byte counters (done / total).
 */
export type ProgressCounts = {
  /**
   * Bytes processed so far.
   */
  bytesDone: number;
  /**
   * Total bytes to process.
   */
  bytesTotal: number;
};
