// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task's terminal status on the wire.
 */
export type TaskStatusDto = "succeeded" | "cancelled" | "failed";
