// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatusDto } from "./TaskStatusDto";

/**
 * One task's terminal result, carrying its output-path claim.
 *
 * This is the per-task projection the completion UI reads to surface where each
 * produced file/folder landed or which existing destination was kept.
 * `output_path` is empty when the task claims no path.
 */
export type TaskResultDto = {
  /**
   * The raw task id.
   */
  taskId: number;
  /**
   * The output base name, e.g. `"photo_001.zip"` (Zip mode) or the folder
   * name (Folder mode).
   */
  outputName: string;
  /**
   * The absolute output path the task wrote to or kept; empty when the task
   * claims no output path.
   */
  outputPath: string;
  /**
   * The task's terminal status.
   */
  status: TaskStatusDto;
  /**
   * The human-readable explanation for a failed or skipped task.
   */
  reason: string | null;
};
