// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatusDto } from "./TaskStatusDto";

/**
 * One task's terminal result, carrying its absolute output path.
 *
 * This is the per-task projection the completion UI reads to surface where each
 * produced file/folder landed. The `output_path` is computed in the presentation
 * layer from the planned job (PathBuf rendered to a lossy UTF-8 string at this
 * wire boundary), mirroring the engine's destination formula.
 */
export type TaskResultDto = {
  /**
   * The raw task id.
   */
  taskId: number;
  /**
   * The output base name, e.g. `"photo_001.zip"` (Zip mode) or the folder
   * name (Folder mode).
   */
  outputName: string;
  /**
   * The absolute output path the task wrote to.
   */
  outputPath: string;
  /**
   * The task's terminal status.
   */
  status: TaskStatusDto;
  /**
   * The failure reason; `Some` only when `status` is [`TaskStatusDto::Failed`].
   */
  reason: string | null;
};
