// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Byte progress for a single task, keyed by its raw task id.
 */
export type TaskProgressDto = { 
/**
 * The raw task id.
 */
taskId: number, 
/**
 * Bytes processed so far.
 */
bytesDone: number, 
/**
 * Total bytes to process.
 */
bytesTotal: number, 
/**
 * Estimated time remaining for this task, in milliseconds; null when unknown.
 */
etaMs: number | null, };
